事业年报参数
事业单位基本情况：
  制度推行情况：
    已完成岗位设置方案备案  是否
    已完成岗位设置 是否
    实行聘用管理制度 是否
    实行公开招聘制度  是否
  机关服务类单位 是否
  单位性质：
  参公事业单位
  事业单位
  行政机关单位        （配备工勤人员的机关单位： 参公事业单位或行政机关单位，并且存在工勤人员）
  单位主系列岗位 （ps7）
  
  
  非正式人员 加个合同终止时间
                              聘用合同情况   短期合同 中期合同 长期合同 项目合同
                              岗位类别  管理、专技、工勤
 CJREPORT_2017BF
-- 
SELECT substr(COORDINATE,0,InStr(COORDINATE,'-',1)-1) , substr(COORDINATE,InStr(COORDINATE,'-',1)+1,length(COORDINATE)) ,A.*  FROM CJREPORT A
select rowid,a.* from CJREPORT a WHERE TABLENAMES = 'JB_PS2'  and COORDINATE = '21-1'
DELETE CJREPORT a WHERE TABLENAMES = 'JB_PS1'and COORDINATE != '21-1'

select TO_CHAR(BIANMA),a.* from CJREPORT a WHERE areacode='422899'and TABLENAMES = 'PX_PS9'  AND substr(COORDINATE,0,InStr(COORDINATE,'-',1)-1)  = '1'  ORDER BY TO_NUMBER( substr(COORDINATE,InStr(COORDINATE,'-',1)+1,length(COORDINATE)) )
select TO_CHAR(BIANMA),a.* from CJREPORT_bf a WHERE areacode='422899' and TABLENAMES = 'HY_PS6_6'  AND substr(COORDINATE,InStr(COORDINATE,'-',1)+1,length(COORDINATE))  = '1'  ORDER BY TO_NUMBER(  substr(COORDINATE,0,InStr(COORDINATE,'-',1)-1))
UPDATE bs_company SET dwxz='02' where comp_id in(
    select distinct comp_id from bs_staff where staffStatus in('01','02') and staffIdentity in ('16','17','18','19','20','21')  
   )
 select comp_id as 单位编码 from bs_company A where comp_id in(
    select distinct comp_id from bs_staff where staffStatus in('01','02') and staffIdentity in ('16','17','18','19','20','21')  
   )
   select * from SB_DICTIONARIES where label  = 'POLT' and (key = '6' or PARENTKEY = '6')
   CREATE TABLE SB_DICTIONARIES_PX   AS 
  select a.* ,1 AS NUM from SB_DICTIONARIES  a where label = 'SYHY' AND RANK = '1'
  select a.* from SB_DICTIONARIES  a where label = 'SSHY' AND RANK = '2' and PARENTKEY = 'Q'
  INSERT INTO SB_DICTIONARIES_PX
  select a.*,ROWNUM from SB_DICTIONARIES  a where label = 'SYHY' AND KEY IN ('A','P','M','Q85','R90','R91')
SELECT ROWID,A.* FROM SB_DICTIONARIES_PX A WHERE LABEL = 'CLAX'

 P    教育
 M    科学研究、技术服务和地质勘查业
 R90    文化艺术业
 Q85    卫生
 R91    体育
 A    农、林、牧、渔业
 
 SELECT 
 COUNT(1) AS c_1
 ,COUNT(1) AS c_2
 ,SUM(CASE WHEN gytype='01' THEN 1 ELSE 0 END ) c_3
 ,SUM(CASE WHEN gytype='02' THEN 1 ELSE 0 END ) c_4
 ,SUM(CASE WHEN NVL(gytype,'0') NOT IN('01','02') THEN 1 ELSE 0 END ) c_5
 ,SUM(CASE WHEN wcgwszbn='1'  THEN 1 ELSE 0 END ) c_6  
 ,SUM(CASE WHEN wcgwsz='1'  THEN 1 ELSE 0 END ) c_7  
 ,SUM(CASE WHEN pyglzd='1'  THEN 1 ELSE 0 END ) c_8  
 ,SUM(CASE WHEN gkzpzd='1'  THEN 1 ELSE 0 END ) c_9  
 ,SUM(CASE WHEN SUBSTR(sshy,0,1)='P'  THEN 1 ELSE 0 END ) c_10  --教育
 ,SUM(CASE WHEN SUBSTR(sshy,0,1)='M'  THEN 1 ELSE 0 END ) c_11  
 ,SUM(CASE WHEN SUBSTR(sshy,0,3)='R90'  THEN 1 ELSE 0 END ) c_12  
 ,SUM(CASE WHEN SUBSTR(sshy,0,3)='Q85'  THEN 1 ELSE 0 END ) c_13  
 ,SUM(CASE WHEN SUBSTR(sshy,0,3)='R91'  THEN 1 ELSE 0 END ) c_14  
 ,SUM(CASE WHEN SUBSTR(sshy,0,1)='A'  THEN 1 ELSE 0 END ) c_15 
 ,SUM(CASE WHEN NVL(SUBSTR(sshy,0,1),'0') NOT IN ('M','P','A') AND NVL(SUBSTR(sshy,0,3),'0') NOT IN('R90','R91','Q85') THEN 1 ELSE 0 END ) c_16 
 ,'' AS c_17 
 ,'' AS c_18 
 ,SUM(CASE WHEN SUBSTR(politicsType,0,1)='4'  THEN 1 ELSE 0 END ) c_19 
 ,SUM(CASE WHEN SUBSTR(politicsType,0,1)='6'  THEN 1 ELSE 0 END ) c_20 
 ,SUM(CASE WHEN SUBSTR(politicsType,0,1)='7'  THEN 1 ELSE 0 END ) c_21
 ,SUM(STAF_ZZ) +SUM(STAF_LS)AS  C_22
 ,SUM(num_sl) AS C_23
 ,SUM(STAF_ZZ) AS C_24
 ,SUM(num_lw) AS C_25
  ,SUM(STAF_TX) AS C_26
  ,SUBSTR(politicsType,0,1)
 FROM BS_COMPANY A 
 LEFT JOIN ( SELECT SUM(CASE WHEN STAFFSTATUS IN('01','02') THEN 1 ELSE 0 END) AS STAF_ZZ ,SUM(CASE WHEN STAFFSTATUS IN('04','05','09') THEN 1 ELSE 0 END) AS STAF_TX, COMP_ID FROM V_BS_STAFF_SY_ZG WHERE STAFFSTATUS IN('01','02','04','05','09') GROUP BY COMP_ID ) B ON B.COMP_ID=A.COMP_ID
 LEFT JOIN ( SELECT COUNT(STAF_ID) STAF_LS, SUM(DECODE(lwpq,'1',1,0)) AS num_lw ,COMP_ID FROM bs_staff_ls GROUP BY COMP_ID ) C ON C.COMP_ID=A.COMP_ID
 LEFT JOIN ( select SUM(APPROVALNUMBER) as num_sl ,comp_id from bs_organization group by COMP_ID ) D ON D.COMP_ID=A.COMP_ID
 WHERE dwxz='02' AND AREACODE='422826'  AND SUBSTR(politicsType,0,1) IN ('4','6','7')
 GROUP BY  SUBSTR(politicsType,0,1) 
 ORDER BY SUBSTR(politicsType,0,1)
 
 
 SELECT * FROM bs_staff WHERE CJSTAFFSTATUS IS NULL
 UPDATE bs_staff SET CJSTAFFSTATUS=STAFFSTATUS WHERE  CJSTAFFSTATUS IS NULL
 CJSTAFFSTATUS IN('01','02') 
 -- 可能
 UPDATE BS_POSTGRADE SET CJFLAG=0 WHERE ID IN (
select MIN(ID) from BS_POSTGRADE where CJFLAG = 1 and  POSTTYPE IN ('SGGR','SLGR', 'SJGR','JGGR') group by staf_id having count(staf_id) >1
)
-- 学历对不上
 SELECT b.EDUCATION FROM V_BS_STAFF_SY_ZG A  LEFT JOIN BS_EDUCATION B ON A.STAF_ID=B.STAF_ID AND  B.HIGHESTDEGREE='1' WHERE A.AREACODE='422826' 
  AND SUBSTR (EDUCATION, 0, 1) NOT IN ( '2')   AND SUBSTR (EDUCATION, 0, 1) NOT IN ( '3')AND SUBSTR (EDUCATION, 0, 1) NOT IN ( '4')AND SUBSTR (nvl(EDUCATION,'99999'), 1, 1)< 4 AND EDUCATION  NOT in ('13','1A','1B','11','12')  
 SELECT 
 COUNT(1) AS C1
,SUM(DECODE(A.SEX,0,1,0)) as C2
,SUM(DECODE(A.nationality,1,0,1)) as C3
,SUM( CASE WHEN politicsstatus in ('01','02') THEN 1 ELSE 0 END ) AS C4
,SUM(DECODE(B.EDUCATION,'11',1,0)) as C5  
,SUM(DECODE(B.EDUCATION,'12',1,0)) as C6 
,'' AS C7
,SUM( CASE WHEN EDUCATION  in ('13','1A','1B','11','12')  THEN 1 ELSE 0 END ) AS C8
,SUM(DECODE(SUBSTR (EDUCATION, 1, 1),'2',1,0)) as C9
,SUM(DECODE(SUBSTR (EDUCATION, 1, 1),'3',1,0)) as C10
,SUM(DECODE(SUBSTR (EDUCATION, 1, 1),'4',1,0)) as C11
,SUM( CASE WHEN SUBSTR (nvl(EDUCATION,'99999'), 1, 1)>4 THEN 1 ELSE 0 END ) AS C12
,SUM( CASE WHEN SUBSTR(C.VALUE,0,4) -NVL(to_char(BRITHDATE,'yyyy'),SUBSTR(C.VALUE,0,4))  <=35  THEN 1 ELSE 0 END ) AS C13
,SUM( CASE WHEN SUBSTR(C.VALUE,0,4) -to_char(BRITHDATE,'yyyy') BETWEEN 36 AND 40  THEN 1 ELSE 0 END ) AS C14
,SUM( CASE WHEN SUBSTR(C.VALUE,0,4) -to_char(BRITHDATE,'yyyy') BETWEEN 41 AND 45  THEN 1 ELSE 0 END ) AS C15
,SUM( CASE WHEN SUBSTR(C.VALUE,0,4) -to_char(BRITHDATE,'yyyy') BETWEEN 46 AND 50  THEN 1 ELSE 0 END ) AS C16
,SUM( CASE WHEN SUBSTR(C.VALUE,0,4) -to_char(BRITHDATE,'yyyy') BETWEEN 51 AND 54  THEN 1 ELSE 0 END ) AS C17
,SUM( CASE WHEN SUBSTR(C.VALUE,0,4) -to_char(BRITHDATE,'yyyy') BETWEEN 55 AND 59  THEN 1 ELSE 0 END ) AS C18
,SUM( CASE WHEN SUBSTR(C.VALUE,0,4) -to_char(BRITHDATE,'yyyy') >= 60 THEN 1 ELSE 0 END ) AS C19
,SUM( DECODE(SUBSTR(classType,0,1),'1',1,0)) AS C20
,SUM( DECODE(SUBSTR(classType,0,1),'3',1,0)) AS C21
,SUM( DECODE(SUBSTR(classType,0,1),'2',1,0)) AS C22
,SUM( DECODE(SUBSTR(classType,0,1),'5',1,0)) AS C23
,SUM( DECODE(SUBSTR(classType,0,1),'8',1,0)) AS C24
,SUM( DECODE(SUBSTR(classType,0,1),'9',1,0)) AS C25
,SUM( DECODE(SUBSTR(classType,0,1),'7',1,0)) AS C26
,SUM( DECODE(SUBSTR(classType,0,1),'6',1,0)) AS C27
,SUM( DECODE(SUBSTR(classType,0,1),'A',1,0)) AS C28
,'' AS C29
,'' AS C30 
,SUM(CASE WHEN SUBSTR(politicsType,0,1)='4'  THEN 1 ELSE 0 END ) C31 
,SUM(CASE WHEN SUBSTR(politicsType,0,1)='6'  THEN 1 ELSE 0 END ) C32 
,SUM(CASE WHEN SUBSTR(politicsType,0,1)='7'  THEN 1 ELSE 0 END ) C33
,TWOPOSTS
 FROM V_BS_STAFF_SY_ZG A 
 LEFT JOIN BS_EDUCATION B ON A.STAF_ID=B.STAF_ID AND  B.HIGHESTDEGREE='1' 
 LEFT JOIN ZJ_DUAL C ON C.ID = 'RW15' --上报时间
 LEFT JOIN BS_POSTGRADE D ON CJFLAG = '1' AND A.STAF_ID=D.STAF_ID  AND POSTTYPE IN ('SGGR','SLGR', 'SJGR','JGGR') AND TWOPOSTS like '04%'
 WHERE 1=1 AND A.AREACODE='422826' 
  (postGradeType='03' and TWOPOSTS like '04%' )

 
-- ps3 新报表 去掉6列
UPDATE CJREPORT SET COORDINATE = TO_NUMBER(  substr(COORDINATE,0,InStr(COORDINATE,'-',1)-1))||'-'||( TO_NUMBER(  substr(COORDINATE,InStr(COORDINATE,'-',1)+1,length(COORDINATE)) ) -1 )
WHERE TABLENAMES = 'ZJ_PS3'  AND substr(COORDINATE,InStr(COORDINATE,'-',1)+1,length(COORDINATE))  > 4



SELECT --5247
COUNT(1) C1
,SUM(CASE  WHEN TO_CHAR(B.GRADUATIONDATE,'yyyy')=SUBSTR(C.VALUE,0,4) AND TO_CHAR(enterCompanyDate,'YYYY')=SUBSTR(C.VALUE,0,4)  THEN 1 ELSE 0 END) AS C2
,SUM(CASE  WHEN TO_CHAR(B.GRADUATIONDATE,'yyyy')!=SUBSTR(C.VALUE,0,4) AND TO_CHAR(enterCompanyDate,'YYYY')=SUBSTR(C.VALUE,0,4)  THEN 1 ELSE 0 END) AS C3
,SUM(CASE  WHEN TO_CHAR(enterCompanyDate,'YYYY')=SUBSTR(C.VALUE,0,4)  THEN 1 ELSE 0 END) AS C4
,'' AS C5
,'' AS C6
,SUM(CASE WHEN jkfs IN ('3','4')AND TO_CHAR(enterCompanyDate,'YYYY')=SUBSTR(C.VALUE,0,4)  THEN 1 ELSE 0 END) AS C7
,SUM(CASE WHEN DDYEAR=SUBSTR(C.VALUE,0,4)  THEN 1 ELSE 0 END) AS C8  -- 交流   调入人员
,SUM(CASE WHEN CHANGEREASONS='16' AND TO_CHAR(POSTSTARTDATE,'YYYY')=SUBSTR(C.VALUE,0,4)   THEN 1 ELSE 0 END) AS C9 -- 交流   调入人员
,SUM(CASE WHEN E.SUBSTAFFTYPE IN ('2','3','4' ) AND TO_CHAR(PENSIONDATE,'YYYY')=SUBSTR(C.VALUE,0,4)   THEN 1 ELSE 0 END) AS C10 -- TX
,SUM(CASE WHEN E.SUBSTAFFTYPE IN ('10' ) AND TO_CHAR(PENSIONDATE,'YYYY')=SUBSTR(C.VALUE,0,4)   THEN 1 ELSE 0 END) AS C12 -- TX
,SUM(CASE WHEN E.SUBSTAFFTYPE IN ('6','7' ) AND TO_CHAR(PENSIONDATE,'YYYY')=SUBSTR(C.VALUE,0,4)   THEN 1 ELSE 0 END) AS C14 -- TX
FROM V_BS_STAFF_SY_ZG A  
LEFT JOIN BS_EDUCATION B ON A.STAF_ID=B.STAF_ID AND HIGHESTDEGREE = '1'
LEFT JOIN ZJ_DUAL C ON C.ID = 'RW15' --上报时间
LEFT JOIN ( SELECT STAF_ID,to_char(ENROLLMENTDATE,'yyyy') AS DDYEAR FROM BS_TRANSFER GROUP BY STAF_ID,to_char(ENROLLMENTDATE,'yyyy') ) D ON D.STAF_ID=A.STAF_ID
LEFT JOIN BS_SUBSTAFF E ON  A.STAF_ID=E.STAF_ID AND SUBSTAFFTYPE in ('2','3','4'  ,'10'  ,'6','7')  
WHERE A.AREACODE='422826'

---

SELECT  A.* from SB_DICTIONARIES SB LEFT JOIN (
SELECT COUNT(1)AS C4 ,DECODE(postGradeType,'03',POSTNAME,TWOPOSTS) SNONE FROM V_BS_STAFF_SY_ZG A WHERE SUBSTR(DECODE(postGradeType,'03',POSTNAME,TWOPOSTS),0,2) ='03' 
GROUP BY DECODE(postGradeType,'03',POSTNAME,TWOPOSTS)  
 ) A ON  SB.KEY =SNONE
WHERE  SB.label  = 'SJGR'   AND SB.RANK='2'  -- 专技在岗人数
  ORDER BY KEY   

SELECT  A.* from SB_DICTIONARIES SB LEFT JOIN (
SELECT COUNT(1)AS C5 ,POSTNAME  SNONE FROM V_BS_STAFF_SY_ZG  A WHERE postGradeType='03' and SUBSTR(TWOPOSTS,0,2) ='04' AND SUBSTR(POSTNAME,0,2) ='03' AND AREACODE='422826'
GROUP BY POSTNAME
 ) A ON  SB.KEY =SNONE
WHERE  SB.label  = 'SJGR'   AND SB.RANK='2' -- 专技在管理岗位
  ORDER BY KEY   
  
-- PS6 分行业
SELECT  A.* from (SELECT DECODE(RANK,1,KEY,NULL)  AS KEY,NUM FROM SB_DICTIONARIES_PX A WHERE LABEL = 'PS06' ) SB LEFT JOIN (
SELECT 
SUM(C1) C1,SUM(C2) C2,SUM(C3) C3,SUM(C4) C4,SUM(C5) C5,SUM(C6) C6,SUM(C7) C7,SUM(C8) C8,SUM(C9) C9,SUM(C10) C10,
SUM(C11) C11,SUM(C12) C12,SUM(C13) C13,SUM(C14) C14,SUM(C15) C15,NVL(SUM(C16),0)+NVL(SUM(C161),0) C16,NVL(SUM(C17),0)+NVL(SUM(C171),0) C17,NVL(SUM(C18),0)+NVL(SUM(C181),0) C18,SUM(C19) C19,SUM(C20) C20,
SUM(C21) C21,SUM(C22) C22,SUM(C23) C23,SUM(C24) C24,SUM(C25) C25,SUM(C26) C26,SUM(C27) C27,SUM(C28) C28,SUM(C29) C29,SUM(C30) C30,
SUM(C31) C31,SUM(C32) C32,SUM(C33) C33,SUM(C34) C34,SUM(C35) C35,SUM(C36) C36,NVL(SUM(C37),0)+NVL(SUM(C371),0) C37,NVL(SUM(C38),0)+NVL(SUM(C381),0) C38,NVL(SUM(C39),0)+NVL(SUM(C391),0) C39,SUM(C40) C40,
SUM(C41) C41,SUM(C42) C42,SUM(C43) C43,SUM(C44) C44,SUM(C45) C45,SUM(C46) C46,SUM(C47) C47,SUM(C48) C48,SUM(C49) C49,SUM(C50) C50,
SUM(C51) C51,SUM(C52) C52,NVL(SUM(C53),0)+NVL(SUM(C531),0) C53,NVL(SUM(C54),0)+NVL(SUM(C541),0) C54,NVL(SUM(C55),0)+NVL(SUM(C551),0) C55
,SUBSTR(SSHY,0,1) AS SNONE
FROM V_BS_COMPANY_SY A 
LEFT JOIN (  -- 正式人员
    SELECT  
SUM(CASE WHEN SUBSTR(TWOPOSTS,0,2)='04' THEN 1 ELSE 0 END ) C1
,SUM(CASE WHEN TWOPOSTS='0401'THEN 1 ELSE 0 END) AS C2
,SUM(CASE WHEN TWOPOSTS='0402'THEN 1 ELSE 0 END) AS C3
,SUM(CASE WHEN TWOPOSTS='0403'THEN 1 ELSE 0 END) AS C4
,SUM(CASE WHEN TWOPOSTS='0404'THEN 1 ELSE 0 END) AS C5
,SUM(CASE WHEN TWOPOSTS='0405'THEN 1 ELSE 0 END) AS C6
,SUM(CASE WHEN TWOPOSTS='0406'THEN 1 ELSE 0 END) AS C7
,SUM(CASE WHEN TWOPOSTS='0407'THEN 1 ELSE 0 END) AS C8
,SUM(CASE WHEN TWOPOSTS='0408'THEN 1 ELSE 0 END) AS C9
,SUM(CASE WHEN TWOPOSTS='0409'THEN 1 ELSE 0 END) AS C10
,SUM(CASE WHEN TWOPOSTS='0410'THEN 1 ELSE 0 END) AS C11
,SUM(CASE WHEN TWOPOSTS='0499'THEN 1 ELSE 0 END) AS C12
--,'' AS C13
,'' AS C14
,'' AS C15
,SUM(CASE WHEN SUBSTR(TWOPOSTS,0,2)='04' AND SUBSTR(politicsType,0,1)='4'  THEN 1 ELSE 0 END ) AS C16
,SUM(CASE WHEN SUBSTR(TWOPOSTS,0,2)='04' AND SUBSTR(politicsType,0,1)='6'  THEN 1 ELSE 0 END ) AS C17 
,SUM(CASE WHEN SUBSTR(TWOPOSTS,0,2)='04' AND SUBSTR(politicsType,0,1)='7'  THEN 1 ELSE 0 END ) AS C18

,SUM(CASE WHEN SUBSTR(DECODE(postGradeType,'03',POSTNAME,TWOPOSTS),0,2) ='03'  THEN 1 ELSE 0 END ) C19 --  聘用专技 + 双肩挑聘用待遇为专技
,SUM(CASE WHEN DECODE(postGradeType,'03',POSTNAME,TWOPOSTS)='0301'THEN 1 ELSE 0 END) AS C20
,SUM(CASE WHEN DECODE(postGradeType,'03',POSTNAME,TWOPOSTS)='0302'THEN 1 ELSE 0 END) AS C21
,SUM(CASE WHEN DECODE(postGradeType,'03',POSTNAME,TWOPOSTS)='0303'THEN 1 ELSE 0 END) AS C22
,SUM(CASE WHEN DECODE(postGradeType,'03',POSTNAME,TWOPOSTS)='0304'THEN 1 ELSE 0 END) AS C23
,SUM(CASE WHEN DECODE(postGradeType,'03',POSTNAME,TWOPOSTS)='0305'THEN 1 ELSE 0 END) AS C24
,SUM(CASE WHEN DECODE(postGradeType,'03',POSTNAME,TWOPOSTS)='0306'THEN 1 ELSE 0 END) AS C25
,SUM(CASE WHEN DECODE(postGradeType,'03',POSTNAME,TWOPOSTS)='0307'THEN 1 ELSE 0 END) AS C26
,SUM(CASE WHEN DECODE(postGradeType,'03',POSTNAME,TWOPOSTS)='0308'THEN 1 ELSE 0 END) AS C27
,SUM(CASE WHEN DECODE(postGradeType,'03',POSTNAME,TWOPOSTS)='0309'THEN 1 ELSE 0 END) AS C28
,SUM(CASE WHEN DECODE(postGradeType,'03',POSTNAME,TWOPOSTS)='0310'THEN 1 ELSE 0 END) AS C29
,SUM(CASE WHEN DECODE(postGradeType,'03',POSTNAME,TWOPOSTS)='0311'THEN 1 ELSE 0 END) AS C30
,SUM(CASE WHEN DECODE(postGradeType,'03',POSTNAME,TWOPOSTS)='0312'THEN 1 ELSE 0 END) AS C31
,SUM(CASE WHEN DECODE(postGradeType,'03',POSTNAME,TWOPOSTS)='0313'THEN 1 ELSE 0 END) AS C32
,SUM(CASE WHEN DECODE(postGradeType,'03',POSTNAME,TWOPOSTS)='0399'THEN 1 ELSE 0 END) AS C33
--,'' AS C34  -- 非正式人员
,'' AS C35
,'' AS C36
,SUM(CASE WHEN SUBSTR(DECODE(postGradeType,'03',POSTNAME,TWOPOSTS),0,2) ='03' AND SUBSTR(politicsType,0,1)='4'  THEN 1 ELSE 0 END ) AS  C37
,SUM(CASE WHEN SUBSTR(DECODE(postGradeType,'03',POSTNAME,TWOPOSTS),0,2) ='03' AND SUBSTR(politicsType,0,1)='6'  THEN 1 ELSE 0 END ) AS C38 
,SUM(CASE WHEN SUBSTR(DECODE(postGradeType,'03',POSTNAME,TWOPOSTS),0,2) ='03' AND SUBSTR(politicsType,0,1)='7'  THEN 1 ELSE 0 END ) AS C39
,SUM(CASE WHEN postGradeType='03' and SUBSTR(TWOPOSTS,0,2) ='04' AND SUBSTR(POSTNAME,0,2) ='03'  THEN 1 ELSE 0 END ) C40
,SUM(C41) AS C41
,SUM(CASE WHEN SUBSTR(TWOPOSTS,0,2) IN('02','05') THEN 1 ELSE 0 END ) C42 --  工勤技能人员
,SUM(CASE WHEN TWOPOSTS IN('0201','0501') THEN 1 ELSE 0 END ) C43 
,SUM(CASE WHEN TWOPOSTS IN('0202','0502') THEN 1 ELSE 0 END ) C44 
,SUM(CASE WHEN TWOPOSTS IN('0203','0503') THEN 1 ELSE 0 END ) C45 
,SUM(CASE WHEN TWOPOSTS IN('0204','0504') THEN 1 ELSE 0 END ) C46 
,SUM(CASE WHEN TWOPOSTS IN('0205','0505') THEN 1 ELSE 0 END ) C47 
,SUM(CASE WHEN TWOPOSTS IN('0206','0506') THEN 1 ELSE 0 END ) C48 
,SUM(CASE WHEN TWOPOSTS IN('0299','0599') THEN 1 ELSE 0 END ) C49 
--,'' AS C50  -- 非正式人员
,'' AS C51
,'' AS C52
,SUM(CASE WHEN SUBSTR(TWOPOSTS,0,2) IN('02','05') AND SUBSTR(politicsType,0,1)='4'  THEN 1 ELSE 0 END ) AS C53
,SUM(CASE WHEN SUBSTR(TWOPOSTS,0,2) IN('02','05') AND SUBSTR(politicsType,0,1)='6'  THEN 1 ELSE 0 END ) AS C54 
,SUM(CASE WHEN SUBSTR(TWOPOSTS,0,2) IN('02','05') AND SUBSTR(politicsType,0,1)='7'  THEN 1 ELSE 0 END ) AS C55
,A.COMP_ID
FROM V_BS_STAFF_SY_ZG A                                                                                                                                                                                    --         此处已经做了单位关联，已经限制在视图中的单位
LEFT JOIN( SELECT  COUNT(1) AS C41,STAF_ID FROM bs_professionalqualified C1    GROUP BY STAF_ID ) C ON C.STAF_ID=A.STAF_ID -- 保证没人只有一条记录，与主表进行关联
WHERE STAFFSTATUS IN('01','02')  AND A.COMP_ID IN (SELECT COMP_ID FROM CJREPORT_COMP WHERE owner='2') group by a.comp_id
) B ON B.COMP_ID=A.COMP_ID
LEFT JOIN  (    -- 非正式人员
SELECT COMP_ID, SUM(DECODE(GWLB,'04',1,0)) AS C13,SUM(DECODE(NVL(GWLB,'03'),'03',1,0)) AS C34,SUM(DECODE(GWLB,'05',1,0)) AS C50 
,SUM(CASE WHEN GWLB='04' AND SUBSTR(politicsType,0,1)='4'  THEN 1 ELSE 0 END ) AS C161
,SUM(CASE WHEN GWLB='04' AND SUBSTR(politicsType,0,1)='6'  THEN 1 ELSE 0 END ) AS C171
,SUM(CASE WHEN GWLB='04' AND SUBSTR(politicsType,0,1)='7'  THEN 1 ELSE 0 END ) AS C181
,SUM(CASE WHEN NVL(GWLB,'03')='03' AND SUBSTR(politicsType,0,1)='4'  THEN 1 ELSE 0 END ) AS C371
,SUM(CASE WHEN NVL(GWLB,'03')='03' AND SUBSTR(politicsType,0,1)='6'  THEN 1 ELSE 0 END ) AS C381
,SUM(CASE WHEN NVL(GWLB,'03')='03' AND SUBSTR(politicsType,0,1)='7'  THEN 1 ELSE 0 END ) AS C391
,SUM(CASE WHEN GWLB='05' AND SUBSTR(politicsType,0,1)='4'  THEN 1 ELSE 0 END ) AS C531
,SUM(CASE WHEN GWLB='05' AND SUBSTR(politicsType,0,1)='6'  THEN 1 ELSE 0 END ) AS C541
,SUM(CASE WHEN GWLB='05' AND SUBSTR(politicsType,0,1)='7'  THEN 1 ELSE 0 END ) AS C551
FROM V_BS_STAFF_SY_LS GROUP BY COMP_ID ) C ON A.COMP_ID= C.COMP_ID
WHERE 1=1  --&            -- 事业单位，县市州
GROUP BY  SUBSTR(SSHY,0,1) -- 对总大类进行分组
) A ON  KEY=SNONE
ORDER BY NUM      



--LEFT JOIN ( SELECT COMP_ID,SUM(DECODE(NVL(GWLB,'04'),'04',1,0)) AS C13,SUM(DECODE(GWLB,'03',1,0)) AS C34,SUM(DECODE(GWLB,'05',1,0)) AS C50  FROM bs_staff_ls GROUP BY COMP_ID ) B ON B.COMP_ID=A.COMP_ID


268 1
select * from V_BS_STAFF_SY_ZG where areacode = '422826' and STAFFSTATUS IN('01','02') AND STAF_ID IN (SELECT STAF_ID FROM  bs_professionalqualified)

SELECT  SUM(1) AS C41,C2.COMP_ID FROM bs_professionalqualified C1,V_BS_STAFF_SY_ZG C2 WHERE C1.STAF_ID=C2.STAF_ID GROUP BY C2.COMP_ID
SELECT COMP_ID,SUM(DECODE(NVL(GWLB,'04'),'04',1,0)) AS C13,SUM(DECODE(GWLB,'03',1,0)) AS C34,SUM(DECODE(GWLB,'05',1,0)) AS C50  FROM bs_staff_ls WHERE COMP_ID IN (SELECT COMP_ID FROM V_BS_STAFF_SY_ZG WHERE STAFFSTATUS IN('01','02') AND AREACODE='422826')
GROUP BY COMP_ID

--所属行业为空
SELECT * FROM V_BS_STAFF_SY_ZG A WHERE A.STAFFSTATUS IN('01','02') AND SUBSTR(DECODE(postGradeType,'03',POSTNAME,TWOPOSTS),0,2) ='03' 
AND SSHY IS NULL AND A.COMP_ID IN (SELECT COMP_ID FROM CJREPORT_COMP WHERE owner='2')



-- PS10
SELECT 
COUNT(1) AS 总数量
,COUNT(DISTINCT A.STAF_ID) AS 总人次
,COUNT(DISTINCT CASE WHEN SUBSTR(TWOPOSTS,0,2)='04' THEN A.STAF_ID ELSE NULL END ) AS C1
,SUM(CASE WHEN SUBSTR(TWOPOSTS,0,2)='04' AND TRAININGADDRESS in('02') THEN 1 ELSE 0 END ) AS C2 -- 出国
,SUM(CASE WHEN SUBSTR(TWOPOSTS,0,2)='04' AND TRAININGTIME in('01') THEN 1 ELSE 0 END ) AS C3
,SUM(CASE WHEN SUBSTR(TWOPOSTS,0,2)='04' AND TRAININGTIME in ('02','03') THEN 1 ELSE 0 END) AS C4
,SUM(CASE WHEN SUBSTR(TWOPOSTS,0,2)='04' AND TRAININGTIME in('04') THEN 1 ELSE 0 END )  AS C5
,SUM(CASE WHEN SUBSTR(TWOPOSTS,0,2)='04' AND TRAININGTIME in('05') THEN 1 ELSE 0 END ) AS C6
,SUM(CASE WHEN SUBSTR(TWOPOSTS,0,2)='04' THEN 1 ELSE 0 END ) AS C7
,SUM(CASE WHEN SUBSTR(TWOPOSTS,0,2)='04' AND trainingType = '03001'  THEN 1 ELSE 0 END ) AS C8
,SUM(CASE WHEN SUBSTR(TWOPOSTS,0,2)='04' AND trainingType = '03002' THEN 1 ELSE 0 END ) AS C9
,SUM(CASE WHEN SUBSTR(TWOPOSTS,0,2)='04' AND trainingType = '03003' THEN 1 ELSE 0 END ) AS C10
,SUM(CASE WHEN SUBSTR(TWOPOSTS,0,2)='04' AND trainingChannel in ( '030101','030102','030103') THEN 1 ELSE 0 END ) AS C11
,SUM(CASE WHEN SUBSTR(TWOPOSTS,0,2)='04' AND trainingChannel in ( '030201','030202','030203') THEN 1 ELSE 0 END ) AS C12
,SUM(CASE WHEN SUBSTR(TWOPOSTS,0,2)='04' AND trainingChannel in ('03003')THEN 1 ELSE 0 END ) AS C13

,COUNT(DISTINCT CASE WHEN SUBSTR(DECODE(postGradeType,'03',POSTNAME,TWOPOSTS),0,2) ='03' THEN A.STAF_ID ELSE NULL END ) AS C14
,SUM(CASE WHEN SUBSTR(DECODE(postGradeType,'03',POSTNAME,TWOPOSTS),0,2) ='03' AND TRAININGADDRESS in('02') THEN 1 ELSE 0 END ) AS C15 -- 出国
,SUM(CASE WHEN SUBSTR(DECODE(postGradeType,'03',POSTNAME,TWOPOSTS),0,2) ='03' AND TRAININGTIME in('01') THEN 1 ELSE 0 END ) AS C16
,SUM(CASE WHEN SUBSTR(DECODE(postGradeType,'03',POSTNAME,TWOPOSTS),0,2) ='03' AND TRAININGTIME in ('02','03') THEN 1 ELSE 0 END) AS C17
,SUM(CASE WHEN SUBSTR(DECODE(postGradeType,'03',POSTNAME,TWOPOSTS),0,2) ='03' AND TRAININGTIME in('04') THEN 1 ELSE 0 END )  AS C18
,SUM(CASE WHEN SUBSTR(DECODE(postGradeType,'03',POSTNAME,TWOPOSTS),0,2) ='03' AND TRAININGTIME in('05') THEN 1 ELSE 0 END ) AS C19
,SUM(CASE WHEN SUBSTR(DECODE(postGradeType,'03',POSTNAME,TWOPOSTS),0,2) ='03' THEN 1 ELSE 0 END ) AS C20
,SUM(CASE WHEN SUBSTR(DECODE(postGradeType,'03',POSTNAME,TWOPOSTS),0,2) ='03' AND trainingType = '03001'  THEN 1 ELSE 0 END ) AS C21
,SUM(CASE WHEN SUBSTR(DECODE(postGradeType,'03',POSTNAME,TWOPOSTS),0,2) ='03' AND trainingType = '03002' THEN 1 ELSE 0 END ) AS C22
,SUM(CASE WHEN SUBSTR(DECODE(postGradeType,'03',POSTNAME,TWOPOSTS),0,2) ='03' AND trainingType = '03003' THEN 1 ELSE 0 END ) AS C23
,SUM(CASE WHEN SUBSTR(DECODE(postGradeType,'03',POSTNAME,TWOPOSTS),0,2) ='03' AND trainingChannel in ( '030101','030102','030103') THEN 1 ELSE 0 END ) AS C24
,SUM(CASE WHEN SUBSTR(DECODE(postGradeType,'03',POSTNAME,TWOPOSTS),0,2) ='03' AND trainingChannel in ( '030201','030202','030203') THEN 1 ELSE 0 END ) AS C25
,SUM(CASE WHEN SUBSTR(DECODE(postGradeType,'03',POSTNAME,TWOPOSTS),0,2) ='03' AND trainingChannel in ('03003')THEN 1 ELSE 0 END ) AS C26
,COUNT(DISTINCT CASE WHEN SUBSTR(TWOPOSTS,0,2) IN('02','05') THEN A.STAF_ID ELSE NULL END ) AS C27
FROM
V_BS_STAFF_SY_ZG A
INNER JOIN BS_TRAINING B ON A.STAF_ID = B.STAF_ID 
LEFT JOIN ZJ_DUAL C ON C.ID = 'RW15' --上报时间
WHERE
A.STAFFSTATUS in ('02','01')  AND TO_CHAR(B.TRAININGSTARTDATE,'YYYY') = SUBSTR(C.VALUE,0,4) 



-- PS6

SELECT --5247
SUM(CASE  WHEN TO_CHAR(B.GRADUATIONDATE,'yyyy')=SUBSTR(C.VALUE,0,4) AND TO_CHAR(enterCompanyDate,'YYYY')=SUBSTR(C.VALUE,0,4)  THEN 1 ELSE 0 END) AS C3
,SUM(CASE  WHEN TO_CHAR(B.GRADUATIONDATE,'yyyy')!=SUBSTR(C.VALUE,0,4) AND TO_CHAR(enterCompanyDate,'YYYY')=SUBSTR(C.VALUE,0,4)  THEN 1 ELSE 0 END) AS C4
,SUM(CASE  WHEN TO_CHAR(enterCompanyDate,'YYYY')=SUBSTR(C.VALUE,0,4)  THEN 1 ELSE 0 END) AS C5
,'' AS C6
FROM V_BS_STAFF_SY_ZG A  
LEFT JOIN BS_EDUCATION B ON A.STAF_ID=B.STAF_ID AND HIGHESTDEGREE = '1'
LEFT JOIN ZJ_DUAL C ON C.ID = 'RW15' --上报时间
LEFT JOIN ( SELECT STAF_ID,to_char(ENROLLMENTDATE,'yyyy') AS DDYEAR FROM BS_TRANSFER GROUP BY STAF_ID,to_char(ENROLLMENTDATE,'yyyy') ) D ON D.STAF_ID=A.STAF_ID
LEFT JOIN BS_SUBSTAFF E ON  A.STAF_ID=E.STAF_ID AND SUBSTAFFTYPE in ('2','3','4' ,'10'  ,'6','7')  
WHERE  STAFFSTATUS IN('01','02')  AND A.COMP_ID IN (SELECT COMP_ID FROM CJREPORT_COMP WHERE owner='2')

 AND AREACODE='422826' --AND SUBSTR(TWOPOSTS,0,2) ='04'        
 
 --------------------------------------------------------------------------------------------------数据查错--
 SELECT  
A.STAF_ID
,A.STAF_NAME
,B.DWXZ  /*单位性质 */
,B.politicstype
,(SELECT VALUE  FROM SB_DICTIONARIES WHERE Key = B.politicstype AND label = 'POLT')  as politicstypelab /* 政区 */
,STAF_IDSL
,sshy
,(SELECT VALUE  FROM SB_DICTIONARIES WHERE Key = B.sshy AND label = 'SSHY') as sshylab /* 所属行业 */
,classType
,(SELECT VALUE  FROM SB_DICTIONARIES WHERE Key = B.classType AND label = 'CLAX') as classTypelab /* 系统 */
,gytype
,(SELECT VALUE  FROM SB_DICTIONARIES WHERE Key = B.gytype AND label = 'GYLX') as gytypelab /* 公益类型 */
,B.wcgwszbn
,B.wcgwsz
,B.pyglzd
,B.gkzpzd
,B.jgfw
FROM bs_staff A
inner join BS_COMPANY B on b.comp_id=a.comp_id
left join (SELECT COUNT(STAF_ID) AS STAF_IDSL,STAF_ID,MAX(TWOPOSTS) AS TWOPOSTS,MAX(POSTNAME) AS POSTNAME,MAX(POSTGRADETYPE) POSTGRADETYPE
                FROM  BS_POSTGRADE WHERE  CJFLAG = '1'  AND POSTTYPE   IN ('SGGR','SLGR', 'SJGR','JGGR')  GROUP BY STAF_ID) C ON C.STAF_ID=A.STAF_ID
left join (SELECT staf_id,MAX(EDUCATION),count(1) edusl  
                from BS_EDUCATION B where  B.HIGHESTDEGREE='1' AND (SUBSTR (EDUCATION, 0, 1)  IN ( '2','3','4') OR EDUCATION   in ('13','1A','1B','11','12')   OR  SUBSTR (nvl(EDUCATION,'99999'), 1, 1)>4)  group by staf_id) D ON D.STAF_ID=A.STAF_ID

SELECT * FROM  BS_POSTGRADE WHERE  CJFLAG = '1'  AND POSTTYPE   IN ('SGGR','SLGR', 'SJGR','JGGR') 



SELECT *FROM V_BS_STAFF_SY_ZG WHERE SSHY ='99'










declare 
v_int int;
v_count int;
i_num int:=0;
v_owner varchar2(50):='2';
sqls  clob;
begin
v_int :=0;
--DELETE CJREPORT_COMPJG WHERE TABLENAMES = 'RW23-0' AND OWNER= v_owner;                                                                                    -- 删除结果
--SELECT count(1) into v_count FROM CJREPORT WHERE TABLENAMES = 'RW23-0'  AND substr(COORDINATE,0,InStr(COORDINATE,'-',1)-1)  = '4' ; -- 计算数量 
for x in ( 
          SELECT * FROM CJREPORT WHERE TABLENAMES = 'RW23-0' AND substr(COORDINATE,0,InStr(COORDINATE,'-',1)-1)  = '4'   -- 表
  ) loop     -- for循环开始
  i_num := i_num + 1;
  sqls := x.BIANMA;
   if  x.leixing = 1 then                                                                                                                                                                                  -- 类型为1
        execute immediate  'select count(1) from ('||sqls||')'  into v_int;
        v_int:=NVL(v_int,0);
   elsif x.leixing = 0 then
       -- 787878
       if InStr(sqls,'787878') > 0 then
            sqls:= replace(sqls,'787878','v_owner');
       else
            sqls:= sqls||'AND A.COMP_ID IN (SELECT COMP_ID FROM CJREPORT_COMP WHERE owner='||v_owner;
       end if;
       execute immediate  'select * from ('||sqls||')' into v_int;
       v_int:=NVL(v_int,0);
   end if;
   
   if v_int !=0 then
      INSERT INTO CJREPORT_COMPJG(TABLENAMES,COORDINATE,COUNTBIANMA,OWNER) VALUES(x.TABLENAMES,x.COORDINATE,v_int,v_owner);
      UPDATE ZJ_DUAL SET VALUE=i_num||'/'||v_count||'/'||x.COORDINATE||'/'||x.TABLENAMES WHERE ID ='pro_js';
      COMMIT;
      --dbms_output.put_line(i_num||'_____'||x.leixing||'___'||v_int);
   end if;
   
end loop; -- for 循环结束

end;

                         



declare 
v_int int;
v_count int;
i_num int:=0;
v_owner varchar2(50):='2';
sqls  clob;
begin
v_int :=0;
DELETE CJREPORT_COMPJG WHERE TABLENAMES = 'RW23-0' AND OWNER= v_owner;                                                                                    -- 删除结果
SELECT count(1) into v_count FROM CJREPORT WHERE TABLENAMES = 'RW23-0'  AND substr(COORDINATE,0,InStr(COORDINATE,'-',1)-1)  = '4' ; -- 计算数量 
for x in ( 
          SELECT * FROM CJREPORT WHERE TABLENAMES = 'RW23-0' AND substr(COORDINATE,0,InStr(COORDINATE,'-',1)-1)  = '4'   -- 表
  ) loop     -- for循环开始
  i_num := i_num + 1;
  sqls := x.BIANMA;
   if  x.leixing = 1 then                                                                                                                                                                                  -- 类型为1
        execute immediate  'select count(1) from ('||sqls||')'  into v_int;
        v_int:=NVL(v_int,0);
   elsif x.leixing = 0 then
       -- 787878
       if  InStr(sqls,'787878')>0 then
            sqls:= replace(sqls,'787878','v_owner');
       else
            sqls:= sqls||'AND A.COMP_ID IN (SELECT COMP_ID FROM CJREPORT_COMP WHERE owner='||v_owner||')';
       end if;
       
       execute immediate  'select * from ('||sqls||')' into v_int;
       v_int:=NVL(v_int,0);
   end if;
   
   if v_int !=0 then
      INSERT INTO CJREPORT_COMPJG(TABLENAMES,COORDINATE,COUNTBIANMA,OWNER) VALUES(x.TABLENAMES,x.COORDINATE,v_int,v_owner);
      UPDATE ZJ_DUAL SET VALUE=i_num||'/'||v_count||'/'||x.COORDINATE||'/'||x.TABLENAMES WHERE ID ='pro_js';
      COMMIT;
      --dbms_output.put_line(i_num||'_____'||x.leixing||'___'||v_int);
   end if;
   
end loop; -- for 循环结束

end;